package pojos;
// Generated 18/11/2018 08:37:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Alumno generated by hbm2java
 */
public class Alumno  implements java.io.Serializable {


     private int codUniversidad;
     private Carrera carrera;
     private int ejercicio;
     private int codFacultad;
     private int correlativo;
     private String nombre;
     private String apellido;
     private Set asignacions = new HashSet(0);

    public Alumno() {
    }

	
    public Alumno(int codUniversidad, Carrera carrera, int ejercicio, int codFacultad, int correlativo) {
        this.codUniversidad = codUniversidad;
        this.carrera = carrera;
        this.ejercicio = ejercicio;
        this.codFacultad = codFacultad;
        this.correlativo = correlativo;
    }
    public Alumno(int codUniversidad, Carrera carrera, int ejercicio, int codFacultad, int correlativo, String nombre, String apellido, Set asignacions) {
       this.codUniversidad = codUniversidad;
       this.carrera = carrera;
       this.ejercicio = ejercicio;
       this.codFacultad = codFacultad;
       this.correlativo = correlativo;
       this.nombre = nombre;
       this.apellido = apellido;
       this.asignacions = asignacions;
    }
   
    public int getCodUniversidad() {
        return this.codUniversidad;
    }
    
    public void setCodUniversidad(int codUniversidad) {
        this.codUniversidad = codUniversidad;
    }
    public Carrera getCarrera() {
        return this.carrera;
    }
    
    public void setCarrera(Carrera carrera) {
        this.carrera = carrera;
    }
    public int getEjercicio() {
        return this.ejercicio;
    }
    
    public void setEjercicio(int ejercicio) {
        this.ejercicio = ejercicio;
    }
    public int getCodFacultad() {
        return this.codFacultad;
    }
    
    public void setCodFacultad(int codFacultad) {
        this.codFacultad = codFacultad;
    }
    public int getCorrelativo() {
        return this.correlativo;
    }
    
    public void setCorrelativo(int correlativo) {
        this.correlativo = correlativo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public Set getAsignacions() {
        return this.asignacions;
    }
    
    public void setAsignacions(Set asignacions) {
        this.asignacions = asignacions;
    }




}


