package pojos;
// Generated 18/11/2018 08:37:35 AM by Hibernate Tools 4.3.1



/**
 * Asignacion generated by hbm2java
 */
public class Asignacion  implements java.io.Serializable {


     private int noAsignacion;
     private Alumno alumno;
     private int ejercicio;
     private int codCarrera;
     private int correlativo;
     private int codFacultad;

    public Asignacion() {
    }

    public Asignacion(int noAsignacion, Alumno alumno, int ejercicio, int codCarrera, int correlativo, int codFacultad) {
       this.noAsignacion = noAsignacion;
       this.alumno = alumno;
       this.ejercicio = ejercicio;
       this.codCarrera = codCarrera;
       this.correlativo = correlativo;
       this.codFacultad = codFacultad;
    }
   
    public int getNoAsignacion() {
        return this.noAsignacion;
    }
    
    public void setNoAsignacion(int noAsignacion) {
        this.noAsignacion = noAsignacion;
    }
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }
    public int getEjercicio() {
        return this.ejercicio;
    }
    
    public void setEjercicio(int ejercicio) {
        this.ejercicio = ejercicio;
    }
    public int getCodCarrera() {
        return this.codCarrera;
    }
    
    public void setCodCarrera(int codCarrera) {
        this.codCarrera = codCarrera;
    }
    public int getCorrelativo() {
        return this.correlativo;
    }
    
    public void setCorrelativo(int correlativo) {
        this.correlativo = correlativo;
    }
    public int getCodFacultad() {
        return this.codFacultad;
    }
    
    public void setCodFacultad(int codFacultad) {
        this.codFacultad = codFacultad;
    }




}


