package pojos;
// Generated 18/11/2018 08:37:35 AM by Hibernate Tools 4.3.1



/**
 * AsignacionDetalle generated by hbm2java
 */
public class AsignacionDetalle  implements java.io.Serializable {


     private int idAsignacion;
     private Curso curso;
     private int noAsignacion;

    public AsignacionDetalle() {
    }

    public AsignacionDetalle(int idAsignacion, Curso curso, int noAsignacion) {
       this.idAsignacion = idAsignacion;
       this.curso = curso;
       this.noAsignacion = noAsignacion;
    }
   
    public int getIdAsignacion() {
        return this.idAsignacion;
    }
    
    public void setIdAsignacion(int idAsignacion) {
        this.idAsignacion = idAsignacion;
    }
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }
    public int getNoAsignacion() {
        return this.noAsignacion;
    }
    
    public void setNoAsignacion(int noAsignacion) {
        this.noAsignacion = noAsignacion;
    }




}


