package pojos;
// Generated 18/11/2018 08:37:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Carrera generated by hbm2java
 */
public class Carrera  implements java.io.Serializable {


     private int codCarrera;
     private Facultad facultad;
     private int codFacultad;
     private String descripcion;
     private Set alumnos = new HashSet(0);

    public Carrera() {
    }

	
    public Carrera(int codCarrera, Facultad facultad, int codFacultad) {
        this.codCarrera = codCarrera;
        this.facultad = facultad;
        this.codFacultad = codFacultad;
    }
    public Carrera(int codCarrera, Facultad facultad, int codFacultad, String descripcion, Set alumnos) {
       this.codCarrera = codCarrera;
       this.facultad = facultad;
       this.codFacultad = codFacultad;
       this.descripcion = descripcion;
       this.alumnos = alumnos;
    }
   
    public int getCodCarrera() {
        return this.codCarrera;
    }
    
    public void setCodCarrera(int codCarrera) {
        this.codCarrera = codCarrera;
    }
    public Facultad getFacultad() {
        return this.facultad;
    }
    
    public void setFacultad(Facultad facultad) {
        this.facultad = facultad;
    }
    public int getCodFacultad() {
        return this.codFacultad;
    }
    
    public void setCodFacultad(int codFacultad) {
        this.codFacultad = codFacultad;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Set alumnos) {
        this.alumnos = alumnos;
    }




}


