package pojos;
// Generated 18/11/2018 08:37:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Curso generated by hbm2java
 */
public class Curso  implements java.io.Serializable {


     private int codCurso;
     private String descripcion;
     private Integer codCursoPrerreq;
     private int credditos;
     private Set asignacionDetalles = new HashSet(0);

    public Curso() {
    }

	
    public Curso(int codCurso, int credditos) {
        this.codCurso = codCurso;
        this.credditos = credditos;
    }
    public Curso(int codCurso, String descripcion, Integer codCursoPrerreq, int credditos, Set asignacionDetalles) {
       this.codCurso = codCurso;
       this.descripcion = descripcion;
       this.codCursoPrerreq = codCursoPrerreq;
       this.credditos = credditos;
       this.asignacionDetalles = asignacionDetalles;
    }
   
    public int getCodCurso() {
        return this.codCurso;
    }
    
    public void setCodCurso(int codCurso) {
        this.codCurso = codCurso;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getCodCursoPrerreq() {
        return this.codCursoPrerreq;
    }
    
    public void setCodCursoPrerreq(Integer codCursoPrerreq) {
        this.codCursoPrerreq = codCursoPrerreq;
    }
    public int getCredditos() {
        return this.credditos;
    }
    
    public void setCredditos(int credditos) {
        this.credditos = credditos;
    }
    public Set getAsignacionDetalles() {
        return this.asignacionDetalles;
    }
    
    public void setAsignacionDetalles(Set asignacionDetalles) {
        this.asignacionDetalles = asignacionDetalles;
    }




}


