package pojos;
// Generated 18/11/2018 08:37:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Facultad generated by hbm2java
 */
public class Facultad  implements java.io.Serializable {


     private int codUniversidad;
     private Universidad universidad;
     private int codFacultad;
     private String descripcion;
     private Set carreras = new HashSet(0);

    public Facultad() {
    }

	
    public Facultad(Universidad universidad, int codFacultad) {
        this.universidad = universidad;
        this.codFacultad = codFacultad;
    }
    public Facultad(Universidad universidad, int codFacultad, String descripcion, Set carreras) {
       this.universidad = universidad;
       this.codFacultad = codFacultad;
       this.descripcion = descripcion;
       this.carreras = carreras;
    }
   
    public int getCodUniversidad() {
        return this.codUniversidad;
    }
    
    public void setCodUniversidad(int codUniversidad) {
        this.codUniversidad = codUniversidad;
    }
    public Universidad getUniversidad() {
        return this.universidad;
    }
    
    public void setUniversidad(Universidad universidad) {
        this.universidad = universidad;
    }
    public int getCodFacultad() {
        return this.codFacultad;
    }
    
    public void setCodFacultad(int codFacultad) {
        this.codFacultad = codFacultad;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getCarreras() {
        return this.carreras;
    }
    
    public void setCarreras(Set carreras) {
        this.carreras = carreras;
    }




}


