package pojos;
// Generated 18/11/2018 08:37:35 AM by Hibernate Tools 4.3.1



/**
 * Universidad generated by hbm2java
 */
public class Universidad  implements java.io.Serializable {


     private int codUniversidad;
     private String descripcion;
     private Facultad facultad;

    public Universidad() {
    }

	
    public Universidad(int codUniversidad) {
        this.codUniversidad = codUniversidad;
    }
    public Universidad(int codUniversidad, String descripcion, Facultad facultad) {
       this.codUniversidad = codUniversidad;
       this.descripcion = descripcion;
       this.facultad = facultad;
    }
   
    public int getCodUniversidad() {
        return this.codUniversidad;
    }
    
    public void setCodUniversidad(int codUniversidad) {
        this.codUniversidad = codUniversidad;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Facultad getFacultad() {
        return this.facultad;
    }
    
    public void setFacultad(Facultad facultad) {
        this.facultad = facultad;
    }




}


